### ISSUE TITLE
Questions about computing hypergradient

### ISSUE THREAD

**Issue by hi-zhenyu** [lorraine2/implicit-hyper-opt#2]
In the paper, the hyper gradients are computed as shown in Algorithm 2.
<img width="567" alt="image" src="https://user-images.githubusercontent.com/22835933/102487759-09e9d400-40a6-11eb-975d-979af0db653e.png">

However, it is inconsistent with the code in train.py & train_augment_net2.py as below:
![image](https://user-images.githubusercontent.com/22835933/102488024-664cf380-40a6-11eb-93be-6feb3d11c670.png)

It seems that indirect_grad should be computed (as shown in the Algorithm 2) by
`
gather_flat_grad(
            grad(d_train_loss_d_lambda, w, grad_outputs=preconditioner.view(-1)))
`

**Comment by lorraine2** [comment]
What is in the code is correct. I believe the algorithm block that you have a screenshot of is from the arXiv version of the paper.  This is a typo in Algorithm 2 (and there's another one in Algorithm 3).  Please check the version in proceedings for AISTATS here: [http://proceedings.mlr.press/v108/lorraine20a/lorraine20a.pdf](http://proceedings.mlr.press/v108/lorraine20a/lorraine20a.pdf)

Sorry for any confusion this may have caused!
